### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by sacdallago** [MusicConnectionMachine/api#1]
The way things stand now, in order to avoid duplicating efforts and in order to have **one, globally accepted solution**, here is what we tutors came up with [simplified]:
1. One API for group 1&2 with one database (Postgres). The API will be coded **HERE** (in this repo) **JOINTLY** by @MusicConnectionMachine/group-1, @MusicConnectionMachine/group-2  @MusicConnectionMachine/group-3 and @MusicConnectionMachine/group-4 (you already have write access on this repo, make good use of it).
2. Group 1,2,3&4 decide upon table definitions **HERE**.
3. Group 1,2,3&4 work independently on their data sources.
4. Group 1,2,3 & 4 use POST/PUT requests to populate the database that is exported via the API here.
5. Group 5 & 6 get GET requests to get the data.

-----
## A bit more about point 4:

You can write an entry script for your npm scripts that populate the database **through the API**. Ideally, something like:
```bash
$ npm install -g musicMachineGroup3
$ musicMachineGroup3 --help

  musicMachineGroup3 v 1.0

  Required:
  --script relationships

  Optionals:
  [-- output] /path/to/folder/nameOfFile.json
  [-- api] http[s]://api.domain.com

$ musicMachineGroup3 --script relationships --api https://hello.party.people
```

-----
## So what do you have to do _now_?
1. @MusicConnectionMachine/group-1 and @MusicConnectionMachine/group-2 already have started writing some API skeleton in their repos. Join efforts and write **one coherent** API here with **ORM** definitions. Same with database. Set this repo up to have a Dockerfile to create the node API container and a Dockerfile to create the Postgres container (you can get inspired here https://github.com/tpca/mecu-postgres) (on the presentation days we can look at this together with other teams)
2. The API defines the schema via ORM (Use Sequelize)! If you want to see how I can give you access to a private repo where I did it a while back [comment with @sacdallago give me access to private repo]
3. @MusicConnectionMachine/group-5  @MusicConnectionMachine/group-6  start defining here (in the issues, not this one) which calls they need. One issue per route request, **consistent** issue formatting, e.g.:

Issue #xy
> **GET** /some/path?q=:id
> :id --> id of an author
> Output:
>   - 200 --> JSON Object, e.g.: `{name: "xyz", location: "cuz"}`
>   - 404 --> no return
>   - 500 --> no return

Issue #yz
> **POST** /some/path?q=:id
> :id --> id of an author
> body --> JSON Object, e.g.: `{comment: "xyz", author: "cuz"}`
> Output:
>   - 201 --> no return
>   - 404 --> no return
>   - 500 --> no return

-----
Questions?
Wanna throw a ninja throwing star at me?

-----
References: 
- https://github.com/MusicConnectionMachine/UnstructuredData/issues/50
- https://github.com/MusicConnectionMachine/StructuredData/pull/24
- https://github.com/MusicConnectionMachine/StructuredData/issues/3
- https://github.com/MusicConnectionMachine/RelationshipsG4/issues/6
- https://github.com/MusicConnectionMachine/VisualizationG6/issues/27
- https://github.com/MusicConnectionMachine/RelationshipsG3/issues/5
- and many more

**Comment by sacdallago** [comment]
P.S.: I would like everyone to give a thumbs up ( 👍 ) to my comment for me to know that you have read it.

And.. get started working too if you can :)

**Comment by nbasargin** [comment]
Could we have one document (maybe on Google Drive?) that contains the current specification? So far there are many good proposals but they are scattered in many discussions/issues/unversioned excel sheets.

**Comment by lukasstreit** [comment]
So we went ahead and created a Google Document with our ideas for the API. Those are calls that we think will work well with the unstructured data and will be good to work with for the other groups. 

The basic idea is to store metadata about the website in the database and the actual website as a file that can be served if requested. Requesting a specific website resource would then return metadata about the website (including occurences) and a download link to the file.

- Group 1: Please tell us how well this works together with your own ideas for the API.

- Other groups: Please let us know what you think about this API structure and if you think you'll need the calls that we listed under nice to have. 

The document can be found [here](https://docs.google.com/document/d/1TjBtrBpeD-v0Q_oqy_b2sM1i8mfR1qLu6cwPUkP8BBk/edit) and should be editable by anyone. Feel free to include your own thoughts and ideas. Please put your stuff under "Group x requirements".

_Edit: small draft of our suggested table structure included_

**Comment by vviro** [comment]
@nyxathid @LukasS96 @Henni Guys, if you haven't yet considered using Swagger (https://swagger.io) for drafting, documenting and implementing the API, please check it out. (see also https://github.com/swagger-api/swagger-node). It has multiple great things going for it (documentation, client library generation for multiple languages, multiple backend platforms) and unless you have a better alternative or a good reason not to use it, we   (@sacdallago @kordianbruck @pfent) all think that this is probably the best way to proceed with the implementation.

**Comment by ShilpaGhanashyamGore** [comment]
@nyxathid : Can you include me to the API project in Swagger ?
username :ShilpaGhanashyamGore

**Comment by ShilpaGhanashyamGore** [comment]
@LukasS96 @nyxathid : We updated the API provided to Group2 .Please review and feed back as we already working on it .
Section 1.1 in https://docs.google.com/document/d/1TjBtrBpeD-v0Q_oqy_b2sM1i8mfR1qLu6cwPUkP8BBk/edit
We are in the university and we can discuss if we need be please let us know.

**Comment by nbasargin** [comment]
@ShilpaGhanashyamGore 
Swagger: I'm totally new to it and will take a look at it tonight. @lgfrbcsgo did the most work so far. Can I still help you after I've familiarized myself with the project?
API: looks fine to me 👍 

Are you going to the meeting tomorrow at 9 AM? We could discuss more details on the exact JSON structure.

**Comment by kordianbruck** [comment]
@nyxathid there is lots to be done with the database and actually coding the api endpoints. Currently they are mostly stubs that do nothing.

**Comment by kordianbruck** [comment]
This issue is obsolete. New issues for the G5/6 APIs will be created.
