### ISSUE TITLE
Implement sequelize to query DB

### ISSUE THREAD

**Issue by felixschorer** [MusicConnectionMachine/api#10]
http://docs.sequelizejs.com/en/v3/

**Comment by felixschorer** [comment]
Group 2 needs a way to interact with the database to store webpage metadata and connections between entities and and webpages.

```
Pages (
    id: 		int, primary key,
    url: 	        varchar,
    filelocation: 	varchar
)

Contains (
    id:		        int, primary key,
    entityId:		int, foreign key(Terms),
    pageId:		int, foreign key(Pages),
    occurrences:	varchar: "[2, 233, 420]"
)

```
`pageId` is a foreign key mapping to `Pages` and `entityId` is a foreign key mapping to a table with all entities.

**Comment by kordianbruck** [comment]
Issue #11 is related

**Comment by sacdallago** [comment]
Mh since #5 seems to going on here: you should now take care of this via https://github.com/MusicConnectionMachine/MusicConnectionMachine.github.io/issues/6

**Comment by kordianbruck** [comment]
@lgfrbcsgo done for now? Maybe create more specific issues for remaining tables that are needed?

**Comment by felixschorer** [comment]
Yep, done!
