### ISSUE TITLE
Map IMSLP link to entity

### ISSUE THREAD

**Issue by chaoran-chen** [MusicConnectionMachine/api#101]
Hey. In order to include our widgets on [IMSLP](http://imslp.org/), we need a function that maps IMSLP URLs to our entity-ids.
I suggest something like that:
```
GET /imslp2entity
params:
* url: string (see examples)
response:
200 -> { entityType: "work"|"artist", entityId: integer }
```
Examples:
* /wiki/Category:Mozart%2C_Wolfgang_Amadeus -> { entityType: 'artist', entityId: 123 }
* /wiki/Abendruhe,_K.Anh.C_9.10_(Mozart,_Wolfgang_Amadeus) -> { entityType: 'work', entityId: 456 }

I guess that @MusicConnectionMachine/group-1 is most qualified for this task..?

**Comment by kordianbruck** [comment]
@angelinrashmi2000 @LukasNavickas whats your update on this?

**Comment by joern-vh** [comment]
Should be fixed by [this](https://github.com/MusicConnectionMachine/VisualizationG5/pull/73).

**Comment by kordianbruck** [comment]
So we don't need a separate endpoint on the API for this?

**Comment by joern-vh** [comment]
No, has been solved by [this](https://github.com/MusicConnectionMachine/VisualizationG5/blob/develop/react/src/StartupService.jsx#L66).
