### ISSUE TITLE
Fix extensive logging

### ISSUE THREAD

**Issue by felixschorer** [MusicConnectionMachine/api#102]
We at @MusicConnectionMachine/group-2 are currently having problems with the very verbose logging of the API submodule. 

It literally spams the console to death and overshadows our own logging which is intended for errors and warnings.

**Comment by chaoran-chen** [comment]
Can't you just grep for your own logging? (Maybe try [--line-buffered](http://stackoverflow.com/questions/7161821/how-to-grep-a-continuous-stream).)

**Comment by Sandr0x00** [comment]
To not log the api-sequelize-stuff, you have to add `logging: false` to the initializing of sequelize. (http://stackoverflow.com/a/28927913)
However, this only worked locally for me, not when I use a `postgres://` string -.-
Therefore I did not change it.
Place to look at: database.js

**Comment by pfent** [comment]
I'd probably go with the approach @chaoran-chen suggested.
However, I'd probably do something along the lines:
```
run.sh | tee out.log
```
then you can easily `grep "needle" out.log` and also watch the whole log output on your console
