### ISSUE TITLE
No API-Key for GET / different API-Keys

### ISSUE THREAD

**Issue by chaoran-chen** [MusicConnectionMachine/api#105]
Currently, one API-Key is used for all request. This must be changed since it would be shipped with the client code and as a consequence be public. I think that the easiest solution is that we don't require a key for the public requests (the GET-requests and maybe some POST-requests for user feedbacks). Another way would be the usage of different API-Keys for public and private requests.

**Comment by Henni** [comment]
For some reason some (maybe all?) swagger path files still contain a parameter `apiKey` which is unnecessary, if not even wrong.

These parameters should be removed and instead we should set the proper security policy.
See: http://swagger.io/docs/specification/authentication/ or https://apihandyman.io/writing-openapi-swagger-specification-tutorial-part-6-defining-security/#operation-level

If this isn't solved in the pre-hack phase I'll find time at the beginning of the hackathon for this.
