### ISSUE TITLE
Increase DB connection limit

### ISSUE THREAD

**Issue by felixschorer** [MusicConnectionMachine/api#108]
Ok, so here's the deal. @MusicConnectionMachine/group-2 started large scale processing 2 hours ago and after spawning just shy of 40 VMs we've noticed that our CPU utilization dropped massively across all machines. The problem turns out to be the DB limiting the maximum amount of concurrent connections.

We've now set the the amount of connections in the connection pool down to a single connection, so we can get some processing done tonight. 10 connections for each of our a processes per VM is just excessive...

This is just a short term solution though. The limit has to be increased as soon as possible.

**Comment by kordianbruck** [comment]
Alright, we'll try to setup a new machine on azure and see if we can do like 10k connections there - shouldn't be a problem hopefully.

@sacdallago

**Comment by sacdallago** [comment]
Döne

**Comment by kordianbruck** [comment]
![istock_000018031252_gbh007](https://cloud.githubusercontent.com/assets/298860/25303752/77600640-2759-11e7-938f-b37bf7988ced.jpg)
