### ISSUE TITLE
Get docs online

### ISSUE THREAD

**Issue by kordianbruck** [MusicConnectionMachine/api#116]
We need to deploy the api docs somewhere. 

Possibly include them within the website of @MusicConnectionMachine/group-6

**Comment by kordianbruck** [comment]
@lgfrbcsgo ideas?

**Comment by yetolas** [comment]
You mean in the wiki page? Or what?

**Comment by kordianbruck** [comment]
@yetolas no, we just wanted to have the docs directly available on the API site/url
