### ISSUE TITLE
Feedback for Relationships

### ISSUE THREAD

**Issue by martomi** [MusicConnectionMachine/api#122]
Similar to #90 we need a feedback API for our relation widget. 

```
POST /relations/:relation_id/report
body --> { comment: "Some optional comment here" }
```

Here's how the UI looks like for reference:
<img width="404" alt="screen shot 2017-04-23 at 14 17 51" src="https://cloud.githubusercontent.com/assets/3739458/25313611/14da83fe-2832-11e7-8208-25252c56ddfb.png">

**Comment by kordianbruck** [comment]
@Binabiko Please add this endpoint similar to the one for events.
