### ISSUE TITLE
Add total search counts to search result

### ISSUE THREAD

**Issue by syncall** [MusicConnectionMachine/api#125]
Can you please include a total field in the /search/entities/ api?
This `total` tells us about the total available search results. Because the response has only a limited size (e.g. 20)

**Comment by syncall** [comment]
The Pagination relies on this

**Comment by Henni** [comment]
any suggestions how the response should look like (e.g. for artists) in combination with #126 ?

**Comment by kordianbruck** [comment]
```json
{
   data: [ ],
   numRows: 9001
}
```
like this?
