### ISSUE TITLE
/search/entities should return works as well

### ISSUE THREAD

**Issue by lustoykov** [MusicConnectionMachine/api#127]
@Henni /search/entities should return works as well

Then @Binabiko needs to test if `mapImpsLink` works as expected in #101

**Comment by Henni** [comment]
`/search/entities` is succeeded by individual queries (see #126 #132).
`/works` now supports filtering and pagination.

**Comment by joern-vh** [comment]
Is the current Version deployed?

**Comment by Henni** [comment]
@Binabiko it should be auto-deployed via dockerhub.
