### ISSUE TITLE
Releases API not working

### ISSUE THREAD

**Issue by syncall** [MusicConnectionMachine/api#128]
If I try to access the releases API it won't work. It produces an
`{"message":"Response validation failed: failed schema validation","code":"SCHEMA_VALIDATION_FAILED","failedValidation":true,"results":{"errors":[{"co` error

Trying http://mcmapi.azurewebsites.net/releases/fec39254-b342-46d6-872c-277ae243e4f3

Does this matter? Heard the Releases are deprecated in favor of works?

**Comment by Henni** [comment]
@sacdallago or @vviro wanted to drop this table in favor of the works table.
Is this correct?

**Comment by sacdallago** [comment]
Correct. Works now contains 110+ items and some new fields in `mcmprod` and the latest API models.
