### ISSUE TITLE
Bugs in search functions

### ISSUE THREAD

**Issue by chaoran-chen** [MusicConnectionMachine/api#134]
There are two bugs in `dsap/search.js`, `return` are missing in:
* https://github.com/MusicConnectionMachine/api/blob/develop/api/dsap/search.js#L32
* https://github.com/MusicConnectionMachine/api/blob/develop/api/dsap/search.js#L45

Furthermore, `searchEntities` searches for artists, instruments, and releases (which will be removed?) but not for works.

**Comment by pfent** [comment]
@Henni any spare time for this?

**Comment by chaoran-chen** [comment]
I can do it later.

**Comment by chaoran-chen** [comment]
Obsolete since the regarding functions were deleted in #139.
