### ISSUE TITLE
Search API for website

### ISSUE THREAD

**Issue by syncall** [MusicConnectionMachine/api#14]
We from team 6 would like to have an API we can query to search through all the entities with one text string. As a result we get a lot of entries (different types: compositions, artists, etc.) If your model of the database is different you can of course adapt the results a bit.

    GET /search?q=:param&from=:from&size=:size
    :param--> some long string that is very unclear about what it wants (Example: romantic piano funny mozart)
    :from --> return results after a certain point (default 0)
    :size --> only return (size) entries

    Output:
        200 --> JSON Object
                  { 
                      success: true,
                      total: 4300,
                      results: [ 
                          {
                                type: "composition/artist/etc.", 
                                id: "1234",
                                name: "xyz", 
                                favorite color: ...,
                                 ...}
                          }, ...
                      ]
                    }
        404 --> `{ 
                      success: true,
                      total: 0,
                      results: []
                    }`
        500 --> error json { success: false} or similar

To get the Information of one entry a simple API like this would be perfect:

    GET /entity/:type/:id
        :type the type of entity (Composition/artist/etc.)
        :id the unique id for one entry

     Output:
        200 --> JSON Object

To make things clear: You don't have to use elasticsearch and this issue is not about autosuggestion

**Comment by simonzachau** [comment]
So you mean you have some random input and want to get a meaningful output?

**Comment by kordianbruck** [comment]
This is tricky. I think we should make an exception for elastic to have it directly access the DB or use PostgreSQLs Fulltext search capabilities. @sacdallago thoughts?

**Comment by syncall** [comment]
@simonzachau basically yes. Similar to Google.

We could set up Elasticsearch ourselves. But we would need full table access for that. That's would make the API fur us useless.. 
And Elasticsearch is actually not really secure (there's a paid plugin) Its intended to be used internally behind an API.

**Comment by kordianbruck** [comment]
@syncall can you use Fulltext search instead? Without using Elastic? Its kinda overkill from what we talked in the last days.

**Comment by syncall** [comment]
As long it gives proper results, I guess thats fine as well. Just I think Elasticsearch would offer much better results and has a Json API already included.

**Comment by syncall** [comment]
And Elasticsearch offers an API for the autocomplete function. This was heavily requested and from my knowledge, wont be implemented so easily with just Postgres

**Comment by kordianbruck** [comment]
Autocomplete is just a history of searched terms. It should also be able to have that implemented in the API. Best if you guys get at it or ask someone form the other groups to do it, otherwise there will be no progress.

**Comment by syncall** [comment]
If you type something in google, the suggested words are definitely not just a history of typed words..
There is no point in implementing something a browser does anyway much better.

So we actually do have to make our own backend now? The last time Christian said we should drop any attempt for that

**Comment by kordianbruck** [comment]
A browser does not do it across multiple users. I mean autocomplete is not a priority right now, getting the search working will be just fine for starters.

Yes, you will have to implement the search functionality - or find a college who will do it for you. Once you do, please assign them here.

**Comment by sacdallago** [comment]
Well, I think the API group(s) can implement a very simple autocomplete feature which matches anything that **starts** with the looked up term. That's how big G just did it. Sometimes they also match words beginning with the search term but inside a sentence (and not just at the _beginning_) of the sentence.

If they create a view for every text element in every table (or full text search, whatever). No?

**Comment by felixschorer** [comment]
What's the current progress on this? I can implement the swagger definitions and a skeleton controller if this hasn't been done yet.

**Comment by Henni** [comment]
@lgfrbcsgo I'm working on the sequelize stuff again now that I'm finished with my exams.
Would be great if you could finish the swagger definitions and maybe also add some controllers if they are still missing. Also take a look at #100 to see if it isn't implemented yet.

**Comment by kordianbruck** [comment]
So we just need the implementation in the controller now - right? @Henni

**Comment by pfent** [comment]
should be done in #114
