### ISSUE TITLE
Overview

### ISSUE THREAD

**Issue by Sandr0x00** [MusicConnectionMachine/api#16]
Here is a graphical visualization of the API and the whole project, like sketched today in the meeting.
If i got something wrong in my drawing, please do not hesitate to write.
Updated after Kordians Announcement in [#17, Comment](https://github.com/MusicConnectionMachine/api/issues/17#issuecomment-287610650)

Place for the WET-Files: https://azure.microsoft.com/en-us/services/storage/blobs/
Drawing with PC: (Every Access to the DB has to be done with [Sequelize](http://docs.sequelizejs.com/en/v3/))
![overview](https://cloud.githubusercontent.com/assets/12230153/24082866/a66c6e08-0ccc-11e7-9887-9c3da755f71b.jpg)
Photo:
![img_20170317_105720](https://cloud.githubusercontent.com/assets/12230153/24042326/cffb89a0-0b11-11e7-931b-09cf9fc4a2ea.jpg)

**Comment by felixschorer** [comment]
Great, thanks! So I guess we have extend the Swagger skeleton some more. Just tag me if you need help or want me to do it.

**Comment by felixschorer** [comment]
One thing though. Will groups 3 and 4 directly interact with the cloud storage or will they go through the API to access it?
The API skeleton is currently setup to do the latter, but this can easily be removed.

**Comment by Sandr0x00** [comment]
As I understand today, in the cloud storage there are only files (many files). We access the links from the DB and then fetch the files directly from the links given there.

**Comment by felixschorer** [comment]
Exactly. I should probably rephrase that. Should the API be a wrapper around the cloud storage? Instead of directly querying the cloud server, you query the API which then in turn queries the cloud storage and returns it as `.json`.

**Comment by Sandr0x00** [comment]
I don't know. Let's move that discussion to an own issue with the whole groups G2/3/4 ;)
#17

**Comment by Sandr0x00** [comment]
Updated Overview after @kordianbruck's [comment](https://github.com/MusicConnectionMachine/api/issues/17#issuecomment-287610650).

**Comment by Sandr0x00** [comment]
Maybe this is not the right place for an overview as well, but where else should it be, because it includes ALL groups and is (from my perspective) important to the success of the whole project.
@kordianbruck @sacdallago

**Comment by kordianbruck** [comment]
Its fine I think. We can close this issue for now. If someone is looking for it, we can reference them here. 

Thanks @Sandr00

**Comment by Sandr0x00** [comment]
To have everything design-related in one place:
Here is the graphical model of the relation stuff: #39
