### ISSUE TITLE
API for commenting

### ISSUE THREAD

**Issue by syncall** [MusicConnectionMachine/api#25]
Hi, for us (Team 6 Visualisation) it would be great to have a functionality for commenting like this:

> PUT /comment
> body --> example: {type: composition, id: 543, text: 'Hi I am David' }

It would be great if the text string could be escaped for any html inside!

> POST /comment
>  body: example: { type: composition, id: 4322, from: 5, size: 10 }
>   200 --> { success: true, comments: JSONArray of results }
>   404 --> { success: false }
>   500 --> { success: false }

This will get all the comments for one entry sorted for the newest ones

References MusicConnectionMachine/VisualizationG6#23

**Comment by syncall** [comment]
A name and date field would be cool as well

**Comment by chaoran-chen** [comment]
This can be closed since we have discarded the plan to develop a comment function as described here?
