### ISSUE TITLE
Latest build on this repository fails - recent contributors check where this originates?

### ISSUE THREAD

**Issue by ShilpaGhanashyamGore** [MusicConnectionMachine/api#38]
Executing (default): SELECT 1+1 AS result
Connection has been established successfully.
Error initializing middleware
Error: Swagger document(s) failed validation so the server cannot start

**Comment by Gillian0023** [comment]
@ShilpaGhanashyamGore Can you start the server before my latest commit(add relationship api(swagger)),I can even not start the server before I began to bulid the relationship stuff,  npm start doesn't work for me. 
Error: can't start "cd ./api/swagger/src/ && multi-file-swagger ./swagger.yaml > ../swagger.json && cd ../../../ && node app.js"

**Comment by ShilpaGhanashyamGore** [comment]
@kordianbruck , @Gillian0023  @LukasS96  - Please check and resolve the build failure as we have to make new commits.

@Gillian0023  yesterday's commits should be checked to see where this originates.

**Comment by Gillian0023** [comment]
@LukasNavickas Did you come across some errors? If not I will delete the latest commit(swagger part) so that they can make new commits

**Comment by ShilpaGhanashyamGore** [comment]
@Gillian0023  : I think the definitions in definitions.yaml are not as per the required structure .You may have the same structure as other definitions (for websites, entities , artisits) .
Generally I follow these steps:
1.make changes to definitions.yml 
2. npm start to verify code compiles 
3.load swagger.json in api\api\swagger onto http://editor.swagger.io/ and check if all the API requests are correctly interpreted by swagger editor , else again we make changes in definitions.yml
4.After swagger editor is happy with your changes you can commit the code.
I think the problem - you mentioned you see may be resovled by changing api-db to 127.0.0.1 in api\config\postgresConfig.json .

**Comment by Gillian0023** [comment]
@ShilpaGhanashyamGore thanks for your suggestions. I will try it later. I have deleted the relationship swagger stuff. I think the sequelize model part should not invoke errors you can review my new commit and make your new commits

**Comment by ShilpaGhanashyamGore** [comment]
@Gillian0023  : thank you . 
sorry but after you removed your changes  is the server running when we give npm start  ?

**Comment by ShilpaGhanashyamGore** [comment]
Issue resolved .
Thank you @Gillian0023 .
