### ISSUE TITLE
Rework Relationship Database Structure

### ISSUE THREAD

**Issue by Henni** [MusicConnectionMachine/api#39]
The outcome of the meeting from @MusicConnectionMachine/group-3 and @MusicConnectionMachine/group-4 

![relation-schema](https://cloud.githubusercontent.com/assets/12230153/24464521/6ff642b4-14aa-11e7-865c-ae01fbc8d160.jpg)
Blue: Planned in #28 
Green: Stuff from other groups, which might be already there
Red: New stuff decided in the meeting

**Comment by simonzachau** [comment]
This is our board draft, @Sandr00 is working on the digital version.
![img_1558](https://cloud.githubusercontent.com/assets/9423641/24450143/085f7f9c-147a-11e7-933c-17e3f0453225.JPG)

**Comment by Sandr0x00** [comment]
@kordianbruck @sacdallago
Could you please give us some short feedback on what you think about this schema?

**Comment by Sandr0x00** [comment]
@kordianbruck @sacdallago 
So we will just implement this now.

**Comment by Henni** [comment]
@vviro we would also like to hear your thoughts on this.
We integrated the possibility to store every relationship we detect even if we can't categorize it. This is done by introducing `rel_str`, `subj_str` and `obj_str` so that we can store a relationship even if we aren't able to set a `subj_id` or `obj_id`.

**Comment by simonzachau** [comment]
starting the work [here](https://github.com/MusicConnectionMachine/api/tree/new-model)

**Comment by kordianbruck** [comment]
@Sandr00 can't see anything *too* wrong with that - proceed

**Comment by Sandr0x00** [comment]
Just added the timeline table from #22.
