### ISSUE TITLE
API Authorization

### ISSUE THREAD

**Issue by felixschorer** [MusicConnectionMachine/api#4]
We're probably going to need API keys for PUT and POST requests.

**Comment by kordianbruck** [comment]
What about DELETE? 

For starters a static key will do just fine.

**Comment by felixschorer** [comment]
Totally forgot about that one, @kordianbruck.

**Comment by kordianbruck** [comment]
As the API is up, please implement a static key auth (through ENV variable configuration) as soon as possible
