### ISSUE TITLE
Set up database

### ISSUE THREAD

**Issue by felixschorer** [MusicConnectionMachine/api#5]
Set up the database so we can start implementing the ORM with [sequelize](http://docs.sequelizejs.com/en/v3/).

**Comment by ShilpaGhanashyamGore** [comment]
@lgfrbcsgo : Is this directed towards Group 1 ? 
If yes , can you elaborate more on the database ? Are you referring to the main Database or the one that we provide for Group 2's purpose only.
We already have a PostGreDB with the following schema 
entity_id , entity_name , entity_type .
We will create a pull request shortly to provide the server .

**Comment by felixschorer** [comment]
@ShilpaGhanashyamGore That's exactly what we need! Nice! 👍 
We'll have to add some tables though to store webpage metadata and "entity <-> webpage" mappings

**Comment by kordianbruck** [comment]
@lgfrbcsgo please leave a comment when closing issues so other people know whats going on. Did you intent to continue the discussion in a different issue?

**Comment by felixschorer** [comment]
@kordianbruck Yes, I've thought that issue #10 is a better fit to discuss the structure of the DB as it goes hand in hand with the implementation of sequelize.
