### ISSUE TITLE
Unable to use API submodule in MusicConnectionMachine/StructuredData

### ISSUE THREAD

**Issue by ShilpaGhanashyamGore** [MusicConnectionMachine/api#52]
@sacdallago  , @kordianbruck  :  git submodule update fails 
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights and the repository exists.
problem
URL : git@github.com:MusicConnectionMachine/api.git is causing problem , it should be 
https@github.com:MusicConnectionMachine/api.git
How do we resolve this ?

**Comment by simonzachau** [comment]
Instead of https @sacdallago wants you to use [this](http://stackoverflow.com/questions/15674064/github-submodule-access-rights-travis-ci/24600210#24600210) I think. [reference](https://github.com/MusicConnectionMachine/RelationshipsG4/pull/39)

**Comment by ShilpaGhanashyamGore** [comment]
It works when you add a SSH key to your git hub account and change the git@something in .gitsubmodules to https@somthehing
