### ISSUE TITLE
Database schema

### ISSUE THREAD

**Issue by Sandr0x00** [MusicConnectionMachine/api#57]
Hey @MusicConnectionMachine/group-1 @MusicConnectionMachine/group-2,
I drew the whole database schema based on the models already in the api and we don't have a connection between the "entities" and the entities table.
Also, we have entites_id in the entities, which is an uuid. I think this should not be there, because Sequelize auto-generated foreign keys with the stuff we do in buildRelations.js
@Henni updated the relationship-tables accordingly (still waiting for approval from some guys from G3/4)
Explanation for inverse-linking, he did: https://github.com/sequelize/sequelize/issues/5144
@ansjin added the event-table (again, approval)

Green Stuff is auto-generated, because of that, the names there may be not correct. (But this only is an overview)
![db-schema](https://cloud.githubusercontent.com/assets/12230153/24544482/c0eb3440-1603-11e7-9137-0d45cb7d7fec.jpg)

**Comment by Sandr0x00** [comment]
Can you please refactor this in a way, that it has the connection?
And have a look at entity_id?

**Comment by kordianbruck** [comment]
@TimHenkelmann can you please create the entity_id as a FK in the releases, instruments, works so that we have a relationship between the two tables. Plus remove the entity_type field in the entity table - Thanks!

**Comment by TimHenkelmann** [comment]
yes, done in #62

**Comment by kordianbruck** [comment]
Thanks!

@Sandr00 can you update the really awesome graph plox?

**Comment by Sandr0x00** [comment]
@kordianbruck done, please check, thank you.

**Comment by Henni** [comment]
This issue should be closed.
Can we move the graphic over to the wiki?
@kordianbruck @sacdallago can you enable the wiki for this repo?

**Comment by kordianbruck** [comment]
Wiki is up.
