### ISSUE TITLE
Move Relationships into models

### ISSUE THREAD

**Issue by Henni** [MusicConnectionMachine/api#59]
Currently the buildRelations file isn't loaded.
So I would suggest to move the relation definitions into the model files and overall base our sequelize structure on the [example app of sequelize](https://github.com/sequelize/express-example).

**Comment by lukasstreit** [comment]
This is basically addressed in #61. 
Sorry for not communicating properly, I didn't see your issue until now.
Please see if you agree with the code in the pull request :+1: 
I moved buildRelations to a new directory, I think it's nice to have all relations in one file.

**Comment by sacdallago** [comment]
#61 merged, this close?
