### ISSUE TITLE
Finalize the APIs Group 1 provides to Group 2 

### ISSUE THREAD

**Issue by ShilpaGhanashyamGore** [MusicConnectionMachine/api#6]
Group 1 has updated the APIs in Section 1.1: 
https://docs.google.com/document/d/1TjBtrBpeD-v0Q_oqy_b2sM1i8mfR1qLu6cwPUkP8BBk/edit
Please feedback .

**Comment by felixschorer** [comment]
Looks good! 👍 
I can create a swagger template for it if you wish. Just like the one in my pull request.

**Comment by ShilpaGhanashyamGore** [comment]
@lgfrbcsgo  : I will have a look at your pull request and create one.Thank you!

**Comment by TimHenkelmann** [comment]
@MusicConnectionMachine/group-2 just to be on the same page about that: We will drop the "entities" table from our PostgreSQL db. We will then create separate tables (via Sequelize) for "artist", "work" , "release" and "instrument" and provide a REST API with Swagger, such that you can access this data. 
Do you have any benefit if we also provide a database dump?

**Comment by kordianbruck** [comment]
This is not needed any longer right? Group 2 will directly access the DB.

Maybe we can reuse this APIs for G5/6
