### ISSUE TITLE
Sequelize cannot connect to postgres

### ISSUE THREAD

**Issue by FelsyWaschbaer** [MusicConnectionMachine/api#73]
When I run **docker-compose build && docker-compose up** on the development branch I get a 
SequelizeConnectionRefusedError. The postgres docker is starting normally though. Is there some information missing in the README file or is there a bug. 

api_1     | { SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:5432
api_1     |     at /usr/src/api/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:98:20
api_1     |     at Connection.<anonymous> (/usr/src/api/node_modules/pg/lib/client.js:185:5)
api_1     |     at emitOne (events.js:96:13)
api_1     |     at Connection.emit (events.js:188:7)
api_1     |     at Socket.<anonymous> (/usr/src/api/node_modules/pg/lib/connection.js:86:10)
api_1     |     at emitOne (events.js:96:13)
api_1     |     at Socket.emit (events.js:188:7)
api_1     |     at emitErrorNT (net.js:1278:8)
api_1     |     at _combinedTickCallback (internal/process/next_tick.js:74:11)
api_1     |     at process._tickDomainCallback (internal/process/next_tick.js:122:9)
api_1     |   name: 'SequelizeConnectionRefusedError',
api_1     |   message: 'connect ECONNREFUSED 127.0.0.1:5432',
api_1     |   parent: 
api_1     |    { Error: connect ECONNREFUSED 127.0.0.1:5432
api_1     |        at Object.exports._errnoException (util.js:1022:11)
api_1     |        at exports._exceptionWithHostPort (util.js:1045:20)
api_1     |        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
api_1     |      code: 'ECONNREFUSED',
api_1     |      errno: 'ECONNREFUSED',
api_1     |      syscall: 'connect',
api_1     |      address: '127.0.0.1',
api_1     |      port: 5432 },
api_1     |   original: 
api_1     |    { Error: connect ECONNREFUSED 127.0.0.1:5432
api_1     |        at Object.exports._errnoException (util.js:1022:11)
api_1     |        at exports._exceptionWithHostPort (util.js:1045:20)
api_1     |        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
api_1     |      code: 'ECONNREFUSED',
api_1     |      errno: 'ECONNREFUSED',
api_1     |      syscall: 'connect',
api_1     |      address: '127.0.0.1',
api_1     |      port: 5432 } }

**Comment by martomi** [comment]
Can you try running `docker-compose up` a second time? I had the same error the first time I ran it. Works from the second time. Seems like the issue is that postgres takes more time to initialize the first time it's started and is not available by the time node tries to connect.

**Comment by FelsyWaschbaer** [comment]
Did not work for me

**Comment by Henni** [comment]
what @martomi described should work.
Stop the currently running instance of `docker-compose up` (Ctrl+C) and rerun `docker-compose up`.

**Comment by FelsyWaschbaer** [comment]
Maybe it should but it doesn't ;-)   Does it still work for you if you do docker-compose build ?

**Comment by Henni** [comment]
I'm looking into it
