### ISSUE TITLE
Perform knitting in dockerfile

### ISSUE THREAD

**Issue by sacdallago** [MusicConnectionMachine/api#86]
[This](https://github.com/MusicConnectionMachine/api/blob/develop/package.json#L28) is one of those things that you don't need to do at _run time_ but, conceptually, at _build time_.

Please transfer the logic to the `Dockerfile` in a series of `RUN xyz` commands. This way the docker image / container is easier to debug as well.

**Comment by sacdallago** [comment]
Also remember to remove [this](https://github.com/MusicConnectionMachine/api/blob/develop/package.json#L30) line, otherwise the compile step will happen on `npm start` anyway

**Comment by Henni** [comment]
I would still keep this as a script inside npm, but don't run it anymore on `prestart`.
Otherwise this would be a hassle to run every time one changes the swagger API definitions.
