### ISSUE TITLE
Azure setup

### ISSUE THREAD

**Issue by Henni** [MusicConnectionMachine/api#88]
The goal is to have a running instance of the API as an App Service which auto-deploys from Dockerhub.

In theory most of the setup is done.

**Comment by Henni** [comment]
Current issue:
```
write /opt/docker/231072.231072/tmp/GetImageBlob750513179: no space left on device
```
Seems to be a confirmed issue: https://social.msdn.microsoft.com/Forums/azure/en-US/968d3c17-f30e-4631-8dea-73f65ebfe491/getting-no-space-left-on-device-error-new-images-not-pulling-as-a-result?forum=windowsazurewebsitespreview

**Comment by Henni** [comment]
Finally!!!
The API is live on Azure http://musicconnectionapi.azurewebsites.net/

Please open a new issue for any problems you experience and mention / assign me.

**Comment by kordianbruck** [comment]
nice! Good job!

**Comment by pfent** [comment]
🎉 Great work!
