### ISSUE TITLE
Database for testing and working on the API?

### ISSUE THREAD

**Issue by martomi** [MusicConnectionMachine/api#89]
Last week we spoke that there's a need for a populated database connected to the API so we can move forward with API implementations and testing. What's the progress on that?

I would like to know if there's a way to populate the database on my local machine with whatever data you already have available so I can do some work on the API.

@Henni, you would probably know how this is progressing?

**Comment by simonzachau** [comment]
@Sandr00 has instructions for you!

**Comment by Sandr0x00** [comment]
Yesterday @kordianbruck gave us the real DB access, currently there are no data there. 

If you are fine with local data, not good data, just data, you can use our test-data:
=> check out our rep: [MusicConnectionMachine/Relationships](https://github.com/MusicConnectionMachine/Relationships)
=> make sure, you have the submodule `api` present (maybe you have to do some `git submodule update --init` and/or `npm install`)
=> start local DB: in the `api` folder do a `docker-compose up`
=> run `example/fillDatabase.js` with Webstorm (or directly with node)

You now should have "some" data in the db:
Data in `artists`, `works`, `releases` was stolen from @MusicConnectionMachine/group-1
Most data in `entities`, `contains`, `websites` is dummy, but the `blob_url`s are "real" data. Stolen from @MusicConnectionMachine/group-2 
You can connect to the local DB via Port `5432`, no password, username `postgres` with any DB-view-tool you like (Examples: [pgAdmin](https://www.pgadmin.org/), [SQL Developer](http://www.oracle.com/technetwork/developer-tools/sql-developer/overview/index-097090.html), ....)

If you need data in `relationships`, `relationshipDescriptions`, `relationshipEntities` you can run `test/simpleTestFile.js` with Webstorm (or directly with node), but you may have to set environment variables or edit the `config/index.js` to a running test-algorithm on Azure. You can use those:
DateEventExtraction: 40.69.44.71 : 80
Ollie: 40.69.64.78 : 80
CoRef: 13.79.163.28 : 80 

I have no test data for you in the other tables.

**Comment by Henni** [comment]
@martomi are you happy with the response by @Sandr00 and can we close this?

**Comment by martomi** [comment]
Yes for now.
