### ISSUE TITLE
Feedback for Events

### ISSUE THREAD

**Issue by chaoran-chen** [MusicConnectionMachine/api#90]
Since our data are collected from the large, wide internet and are not checked by human experts, it would be nice to enable the users to give us feedback about the quality of our data. For feedbacks for the [events](https://github.com/MusicConnectionMachine/api/issues/22), an API-endpoint like the following would be necessary.
```
POST /events/:event_id/feedback
:id --> id of an event
body --> { type: "like"|"dislike"|"wrong_data" }
```
The visualization can be seen in https://github.com/MusicConnectionMachine/VisualizationG5/pull/59.

**Comment by kordianbruck** [comment]
So this issue is then done? @Binabiko 
Tested?

**Comment by joern-vh** [comment]
Yes, Everything discussed yesterday with @sacdallago is implemented and has been tested with @Henni.

**Comment by pfent** [comment]
Closing the issue then…
