### ISSUE TITLE
API for Autocomplete Function

### ISSUE THREAD

**Issue by syncall** [MusicConnectionMachine/api#95]
Hi, we from Team 6 would like to implement some simple Autocomplete Functionality. For this we need the following:
> PUT /autosuggest/:string
> :string --> Some String a user typed (e.g. Mozart). 
> Will be merged into Database. If the String is alreade there, a counter for it is increased

And to retrieve suggestions:

> GET /autosuggest/:string?size=:size
> :string --> something a user types (e.g. Moz)
> :size --> only return size results
> Result: JSONArray with all the matching strings from the databse, that start with :string sorted by the counter

**Comment by chaoran-chen** [comment]
@syncall, is this still up-to-date? Should we attack it?

**Comment by syncall** [comment]
I solved it with cookies. Actually I don't know if we want a cross user autocomplete. If someone writes some bullshit in the search, everyone would get these bullshit suggestions..

**Comment by kordianbruck** [comment]
I actually like the current implementation. So lets leave it at that for now.
