### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by Henni** [MusicConnectionMachine/api#98]
This project should have its own cli interface similar to all the other projects.

@sacdallago do we want this?

**Comment by kordianbruck** [comment]
Why would we want this? The API is running the webserver that answers any calls - what else is there to do? 

Please elaborate other functionality, why this might be useful.

**Comment by sacdallago** [comment]
Yeah. There's no need for a CLI in the API, I don't get this point...

**Comment by Henni** [comment]
Just wanted to make sure whether you requested a cli for *all* projects, or just group 1-4.
